---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  name: Connectivity Test & Display ONTAP Info

  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: true
      confirm: true
  vars:
    netapp_hostname: 192.168.0.101
    netapp_username: admin

  tasks:
  - name: "Collect ONTAP Info"
    na_ontap_info:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    register: info

  - name: Print ONTAP Response
    debug:
      msg: "{{ info }}"


