---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  vars:
    hostname: 192.168.0.101
    vserver: ansible_vserver
    aggr: ansible_lab_01_aggr1
    vol_name: DemoVol
    username: admin
    password: NetApp1!
    
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 3
      size_unit: gb
      policy: default
      wait_for_completion: True
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true

      validate_certs: false



